version: '3.8'
services:
  springapp:
    image: 339712936703.dkr.ecr.ap-south-1.amazonaws.com/springapp:latest
    volumes:
      - /path/on/host:/path/in/container
    ports:
      - "8000:8000"  # Adjust the ports as needed
    environment:
      - SPRING_PROFILES_ACTIVE=default
      # Add other environment variables if needed
