server.port: 8000

spring:
  application.name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gauravgorde/config-server.git
          skipSslValidation: true
          clone-on-start: true
# add username and password if you have a private repo
# username: ${git_username}
# password: ${git_password}     
          
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
eureka.instance.prefer-ip-address: true,
eureka.client.fetch-registry: true,
eureka.client.register-with-eureka: true,
eureka.client.service-url.defaultZone: "http://localhost:7591/eureka"